when a role has been supplied but no build number, fail.- the message about both variable being required is otherwise suppressed for being noisy and misleading

diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -17,7 +17,10 @@ main() {
     echo "  AWS_SECRET_ACCESS_KEY=(${#AWS_SECRET_ACCESS_KEY} chars)"
     echo "  AWS_SESSION_TOKEN=(${#AWS_SESSION_TOKEN} chars)"
   else
-    echo "Missing BUILDKITE_PLUGIN_SSM_ASSUME_ROLE_ARN or BUILDKITE_BUILD_NUMBER"
+    if [ -n "$role" ]; then
+        echo "Error: both BUILDKITE_PLUGIN_SSM_ASSUME_ROLE_ARN and BUILDKITE_BUILD_NUMBER are required to assume role"
+        exit 1
+    fi
   fi
 
   local awsregion=${AWS_DEFAULT_REGION:-ap-southeast-2}
