fix bug where error in assume_role_credentials ignored until unbound variable in AWS_ACCESS_KEY_ID

diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -10,7 +10,14 @@ main() {
 
   if [[ -n $role && -n $build ]]; then
     echo "~~~ Assuming IAM role $role ..."
-    eval "$(assume_role_credentials "$role" "$build" | credentials_json_to_shell_exports)"
+    output="$(assume_role_credentials "$role" "$build" | credentials_json_to_shell_exports)"
+    rc="$?"
+    if [ ! "$rc" -eq 0 ]; then
+        echo "Error: failed to assume role: $rc"
+        exit 1
+    fi
+
+    eval "$output"
 
     echo "Exported session credentials:"
     echo "  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
